### ISSUE TITLE
./bin/dev.js does not seem to work

### ISSUE THREAD

**Issue by bader-nasser** [oclif/hello-world-esm#38]
After cloning the project and installing the deps using `pnpm`, running `node ./bin/dev.js help` does not show the commands!

Also, when I change any thing in the commands (e.g. description) and run `node ./bin/dev.js help hello`, I don't get the new values.

**Comment by bader-nasser** [comment]
@mdonnalley I added these scripts and used them with @oclif/core v3 & v2
```json
    "dev": "ts-node ./bin/dev.js",
    "dev2": "./bin/dev.js",
```

but still nothing is working!

**Comment by mdonnalley** [comment]
@bader-nasser my bad - I forgot that support for auto-transpiling local plugins hasn't been merged yet. It's being added in this PR: https://github.com/oclif/core/pull/779

In the meantime, you'll need to compile your changes first before executing the plugin. 

Also important to note that auto-transpiling ESM plugins is only supported when developing the plugin from the plugin directory. In other words, `bin/dev.js` will auto-transpile but if you were to link the plugin to another plugin, it will not work. More context [here](https://github.com/oclif/core/issues/749#issuecomment-1707359387).

**Comment by bader-nasser** [comment]
For the time being I switched back to v2 and I may wait a lil' bit before using v3 again! Thank you.

**Comment by bader-nasser** [comment]
@mdonnalley I upgraded to latest deps and found the dev bin. is working with:

```js
#!/usr/bin/env -S node --loader ts-node/esm --no-warnings=ExperimentalWarning
```

not:
```js
#!/usr/bin/env ts-node
```

and I don't know why!

I run it using npm script: `"app-dev": "./bin/dev.js",`

https://github.com/bader-nasser/pdftools/blob/main/bin/dev.js

**Comment by mdonnalley** [comment]
@bader-nasser can you elaborate on what you're seeing? I just checked out your repo, ran `yarn`, update the bin/dev.js script and it seems like everything is working as expected

**Comment by bader-nasser** [comment]
@mdonnalley  It works with **node 18** and causes an error with node 20!

I used `pnpm` with and without the following in .npmrc:
```ini
shamefully-hoist = true
public-hoist-pattern[]=*
```

as well as using `npm` and got the following error when using `ts-node` in the shebang:

```bash
$ npm run app-dev -- e -h # and pnpm app-dev e -h
(node:31017) [ERR_UNKNOWN_FILE_EXTENSION] TypeError Plugin: @bader-nasser/pdftools: Unknown file extension ".ts" for .../src/commands/compress/index.ts
module: @oclif/core@3.0.4
task: cacheCommand
plugin: @bader-nasser/pdftools
root: .../pdftools
See more details with DEBUG=*
(Use `node --trace-warnings ...` to show where the warning was created)
(node:31017) [ERR_UNKNOWN_FILE_EXTENSION] TypeError Plugin: @bader-nasser/pdftools: Unknown file extension ".ts" for .../src/commands/convert/index.ts
module: @oclif/core@3.0.4
task: cacheCommand
plugin: @bader-nasser/pdftools
root: .../pdftools
See more details with DEBUG=*
(node:31017) [ERR_UNKNOWN_FILE_EXTENSION] TypeError Plugin: @bader-nasser/pdftools: Unknown file extension ".ts" for .../src/commands/extract/index.ts
module: @oclif/core@3.0.4
task: cacheCommand
plugin: @bader-nasser/pdftools
root: .../pdftools
See more details with DEBUG=*
(node:31017) [ERR_UNKNOWN_FILE_EXTENSION] TypeError Plugin: @bader-nasser/pdftools: Unknown file extension ".ts" for .../src/commands/merge/index.ts
module: @oclif/core@3.0.4
task: cacheCommand
plugin: @bader-nasser/pdftools
root: .../pdftools
See more details with DEBUG=*
(node:31017) [ERR_UNKNOWN_FILE_EXTENSION] TypeError Plugin: @bader-nasser/pdftools: Unknown file extension ".ts" for .../src/commands/process/index.ts
module: @oclif/core@3.0.4
task: cacheCommand
plugin: @bader-nasser/pdftools
root: .../pdftools
See more details with DEBUG=*
(node:31017) [ERR_UNKNOWN_FILE_EXTENSION] TypeError Plugin: @bader-nasser/pdftools: Unknown file extension ".ts" for .../src/commands/repair/index.ts
module: @oclif/core@3.0.4
task: cacheCommand
plugin: @bader-nasser/pdftools
root: .../pdftools
See more details with DEBUG=*
(node:31017) [ERR_UNKNOWN_FILE_EXTENSION] TypeError Plugin: @bader-nasser/pdftools: Unknown file extension ".ts" for .../src/commands/uncompress/index.ts
module: @oclif/core@3.0.4
task: cacheCommand
plugin: @bader-nasser/pdftools
root: .../pdftools
See more details with DEBUG=*
(node:31017) [ERR_UNKNOWN_FILE_EXTENSION] TypeError Plugin: @bader-nasser/pdftools: Unknown file extension ".ts" for .../src/commands/update-metadata/index.ts
module: @oclif/core@3.0.4
task: cacheCommand
plugin: @bader-nasser/pdftools
root: .../pdftools
See more details with DEBUG=*
Error: Command e not found.
    at error (.../node_modules/@oclif/core/lib/errors/index.js:26:15)
    at HelpClass.showHelp (.../node_modules/@oclif/core/lib/help/index.js:221:28)
    at run (.../node_modules/@oclif/core/lib/main.js:68:20)
    at async file:///.../bin/dev.js:4:1
```
